### ISSUE TITLE
Travis's RNGCryptoServiceProvider isn't IDisposable

### ISSUE THREAD

**Issue by defuse** [defuse/password-hashing#55]
```
PasswordHash.cs(46,24): error CS1674: `System.Security.Cryptography.RNGCryptoServiceProvider': type used in a using statement must be implicitly convertible to `System.IDisposable'

/usr/lib/mono/2.0/mscorlib.dll (Location of the symbol related to previous error)

Compilation failed: 1 error(s), 0 warnings

Cannot open assembly 'Test.exe': No such file or directory.

FAIL.

rm: cannot remove `Test.exe': No such file or directory
```

**Comment by defuse** [comment]
Seriously?

**Comment by defuse** [comment]
Yep. Computers suck. Switched to Travis's trusty beta and it fixed it. I'm okay with it not working on Ubuntu 12.04 because they're going against Microsoft documentation...
